version: '3.5'

services:
  dynamo:
    container_name: dynamodb
    image: amazon/dynamodb-local
    networks:
      - backend
    ports:
      - '8000:8000'
    working_dir: /home/dynamodblocal
    command: '-jar DynamoDBLocal.jar -inMemory -sharedDb'

networks:
  backend:
    name: sam-rest-test-network
