AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-rest-test

  Sample SAM Template for sam-rest-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    CodeUri: ./api/build/
    Runtime: nodejs12.x
    Environment:
      Variables: 
        TABLE_NAME: !Ref RelayerTable
        DYNAMO_ENDPOINT: ''

Parameters:
  Stage:
    Type: String
    Default: Dev

Resources:
  RelayerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${AWS::StackName}-${Stage}-relayer-api'
      StageName: !Ref Stage
      ## See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-corsconfiguration.html
      Cors:
        AllowMethods: "'GET,HEAD,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
        AllowOrigin: "'*'"
      ## See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-controlling-access-to-apis.html
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: False ## See https://github.com/awslabs/serverless-application-model/issues/717
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  RelayerGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-${Stage}-relayer-api-get-fn'
      Handler: relayer.get
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref RelayerTable }
      Events:
        GetRelayer:
          Type: Api
          Properties:
            RestApiId: !Ref RelayerApi
            Path: /relayers/{relayerId}
            Method: GET

  RelayerListFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-${Stage}-relayer-api-list-fn'
      Handler: relayer.list
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref RelayerTable }
      Events:
        GetRelayers:
          Type: Api
          Properties:
            RestApiId: !Ref RelayerApi
            Path: /relayers
            Method: GET
    
  RelayerCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-${Stage}-relayer-api-create-fn'
      Handler: relayer.create
      Policies:
        - DynamoDBWritePolicy: { TableName: !Ref RelayerTable }
      Events:
        CreateRelayer:
          Type: Api
          Properties:
            RestApiId: !Ref RelayerApi
            Path: /relayers
            Method: POST

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-${Stage}-user-pool'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${AWS::StackName}-${Stage}-user-pool-web-client'
      GenerateSecret: false

  RelayerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-${Stage}-relayers'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: relayerId
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: relayerId
          KeyType: RANGE


Outputs:
  RelayerApiUrl:
    Description: "API Gateway endpoint URL for current stage"
    Value: !Sub "https://${RelayerApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  UserPoolId:
    Value: !Ref UserPool
    Description: Id for the user pool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  RelayerTableName:
    Value: !Ref RelayerTable