AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-rest-test

  Sample SAM Template for sam-rest-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    CodeUri: ./api/build/
    Runtime: nodejs12.x
    Environment:
      Variables: 
        TABLE_NAME: !Ref RelayerTable
        DYNAMO_ENDPOINT: ''
        ENV: ''

Parameters:
  Stage:
    Type: String
    Default: Dev

Resources:
  RelayerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${AWS::StackName}-${Stage}-relayer-api'
      StageName: !Ref Stage
      TracingEnabled: true
      MethodSettings:
        - ResourcePath: '/*'
          LoggingLevel: 'INFO'
          DataTraceEnabled: true
          HttpMethod: '*'
      ## See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-corsconfiguration.html
      Cors:
        AllowMethods: "'GET,HEAD,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
        AllowOrigin: "'*'"
      ## See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-controlling-access-to-apis.html
      Auth:
        DefaultAuthorizer: LambdaTokenAuthorizer
        AddDefaultAuthorizerToCorsPreflight: False ## See https://github.com/awslabs/serverless-application-model/issues/717
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
          LambdaTokenAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn

  AuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: APIAccessDynamoTables
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: DynamoAssumeRolePolicy
                Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: '*'

  DynamoAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt AuthorizerRole.Arn
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: APIAccessDynamoTables
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AccessDynamoTables
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Query
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:BatchWriteItem
                Resource: '*'

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-${Stage}-api-gateway-authorizer'
      Handler: authorizer.authorize
      Role: !GetAtt AuthorizerRole.Arn
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
          REGION: !Sub '${AWS::Region}'
          CLIENT_ID: !Ref UserPoolClient
          DYNAMO_ROLE: !GetAtt DynamoAccessRole.Arn

  RelayerGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-${Stage}-relayer-api-get-fn'
      Handler: relayer.get
      Events:
        GetRelayer:
          Type: Api
          Properties:
            RestApiId: !Ref RelayerApi
            Path: /relayers/{relayerId}
            Method: GET

  RelayerListFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-${Stage}-relayer-api-list-fn'
      Handler: relayer.list
      Events:
        GetRelayers:
          Type: Api
          Properties:
            RestApiId: !Ref RelayerApi
            Path: /relayers
            Method: GET
    
  RelayerCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-${Stage}-relayer-api-create-fn'
      Handler: relayer.create
      Events:
        CreateRelayer:
          Type: Api
          Properties:
            RestApiId: !Ref RelayerApi
            Path: /relayers
            Method: POST

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-${Stage}-user-pool'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: tenantId
          AttributeDataType: String
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${AWS::StackName}-${Stage}-user-pool-web-client'
      GenerateSecret: false

  RelayerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-${Stage}-relayers'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: relayerId
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: relayerId
          KeyType: RANGE


Outputs:
  RelayerApiUrl:
    Description: "API Gateway endpoint URL for current stage"
    Value: !Sub "https://${RelayerApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  UserPoolId:
    Value: !Ref UserPool
    Description: Id for the user pool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  RelayerTableName:
    Value: !Ref RelayerTable