AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-rest-test

  Sample SAM Template for sam-rest-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  UserPoolName:
    Type: String
    Default: SamRestTestUserPool
  
  UserPoolClientName:
    Type: String
    Default: SamRestTestUserPoolClient

  Stage:
    Type: String
    Default: Dev

Resources:
  SamRestTestRelayerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      ## See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-corsconfiguration.html
      Cors:
        AllowMethods: "'GET,HEAD,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
        AllowOrigin: "'*'"
      ## See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-controlling-access-to-apis.html
      Auth:
        DefaultAuthorizer: SamRestTestAuthorizer
        AddDefaultAuthorizerToCorsPreflight: False ## See https://github.com/awslabs/serverless-application-model/issues/717
        Authorizers:
          SamRestTestAuthorizer:
            UserPoolArn: !GetAtt SamRestTestUserPool.Arn

  SamRestTestRelayerGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./relayer-api/
      Handler: lib.get
      Runtime: nodejs12.x
      Timeout: 20
      Environment:
        Variables: { TABLE_NAME: !Ref SamRestTestRelayerTable, DYNAMO_ENDPOINT: '' }
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref SamRestTestRelayerTable }
      Events:
        GetRelayer:
          Type: Api
          Properties:
            RestApiId: !Ref SamRestTestRelayerApi
            Path: /relayers/{relayerId}
            Method: GET

  SamRestTestRelayerListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./relayer-api/
      Handler: lib.list
      Runtime: nodejs12.x
      Timeout: 20
      Environment:
        Variables: { TABLE_NAME: !Ref SamRestTestRelayerTable, DYNAMO_ENDPOINT: '' }
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref SamRestTestRelayerTable }
      Events:
        GetRelayers:
          Type: Api
          Properties:
            RestApiId: !Ref SamRestTestRelayerApi
            Path: /relayers
            Method: GET
    
  SamRestTestRelayerCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./relayer-api/
      Handler: lib.create
      Runtime: nodejs12.x
      Timeout: 20
      Environment:
        Variables: { TABLE_NAME: !Ref SamRestTestRelayerTable, DYNAMO_ENDPOINT: '' }
      Policies:
        - DynamoDBWritePolicy: { TableName: !Ref SamRestTestRelayerTable }
      Events:
        CreateRelayer:
          Type: Api
          Properties:
            RestApiId: !Ref SamRestTestRelayerApi
            Path: /relayers
            Method: POST

  SamRestTestUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      
  
  SamRestTestUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref SamRestTestUserPool
      ClientName: !Ref UserPoolClientName
      GenerateSecret: false


  SamRestTestRelayerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: relayerId
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: relayerId
          KeyType: RANGE


Outputs:
  RelayerApiUrl:
    Description: "API Gateway endpoint URL for current stage"
    Value: !Sub "https://${SamRestTestRelayerApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  UserPoolId:
    Value: !Ref SamRestTestUserPool
    Description: Id for the user pool
  UserPoolClientId:
    Value: !Ref SamRestTestUserPoolClient
  RelayerTableName:
    Value: !Ref SamRestTestRelayerTable